import type { ThemeStyleClasses } from "@/lib/card-theme-utils";

/** Literal Tailwind classes — keep in sync with card-themes.ts */
export const THEME_STYLES: Record<string, ThemeStyleClasses> = {
  midnight: {
    frontSurface: "bg-slate-900",
    frontText: "text-white",
    surface: "bg-slate-900",
    text: "text-white",
    subtext: "text-slate-400",
    accent: "bg-blue-500",
    accentBarMuted: "bg-slate-600",
    initialsText: "text-white",
    isLightFront: false,
    isLightSurface: false,
  },
  paper: {
    frontSurface: "bg-white",
    frontText: "text-slate-900",
    surface: "bg-white",
    text: "text-slate-900",
    subtext: "text-slate-500",
    accent: "bg-slate-900",
    accentBarMuted: "bg-slate-400",
    initialsText: "text-white",
    isLightFront: true,
    isLightSurface: true,
  },
  azure: {
    frontSurface: "bg-blue-600",
    frontText: "text-white",
    surface: "bg-blue-600",
    text: "text-white",
    subtext: "text-blue-100",
    accent: "bg-white",
    accentBarMuted: "bg-blue-200",
    initialsText: "text-slate-900",
    isLightFront: false,
    isLightSurface: false,
  },
  sand: {
    frontSurface: "bg-stone-100",
    frontText: "text-stone-900",
    surface: "bg-stone-100",
    text: "text-stone-900",
    subtext: "text-stone-500",
    accent: "bg-stone-900",
    accentBarMuted: "bg-stone-400",
    initialsText: "text-white",
    isLightFront: true,
    isLightSurface: true,
  },
  forest: {
    frontSurface: "bg-emerald-900",
    frontText: "text-white",
    surface: "bg-emerald-900",
    text: "text-white",
    subtext: "text-emerald-200/70",
    accent: "bg-emerald-400",
    accentBarMuted: "bg-emerald-600",
    initialsText: "text-slate-900",
    isLightFront: false,
    isLightSurface: false,
  },
  mono: {
    frontSurface: "bg-black",
    frontText: "text-white",
    surface: "bg-black",
    text: "text-white",
    subtext: "text-neutral-400",
    accent: "bg-white",
    accentBarMuted: "bg-neutral-500",
    initialsText: "text-slate-900",
    isLightFront: false,
    isLightSurface: false,
  },
  "teal-split": {
    frontSurface: "bg-stone-100",
    frontText: "text-teal-900",
    surface: "bg-stone-50",
    text: "text-teal-950",
    subtext: "text-teal-700",
    accent: "bg-teal-800",
    accentBarMuted: "bg-teal-400",
    initialsText: "text-white",
    isLightFront: true,
    isLightSurface: true,
  },
  "design-point": {
    frontSurface: "bg-black",
    frontText: "text-white",
    surface: "bg-stone-200",
    text: "text-black",
    subtext: "text-neutral-600",
    accent: "bg-black",
    accentBarMuted: "bg-neutral-400",
    initialsText: "text-white",
    isLightFront: false,
    isLightSurface: true,
  },
  "sage-clinical": {
    frontSurface: "bg-lime-900",
    frontText: "text-white",
    surface: "bg-stone-100",
    text: "text-lime-950",
    subtext: "text-lime-800",
    accent: "bg-amber-500",
    accentBarMuted: "bg-lime-700",
    initialsText: "text-white",
    isLightFront: false,
    isLightSurface: true,
  },
  "hatch-mono": {
    frontSurface: "bg-zinc-900",
    frontText: "text-white",
    surface: "bg-white",
    text: "text-zinc-900",
    subtext: "text-zinc-500",
    accent: "bg-zinc-900",
    accentBarMuted: "bg-zinc-300",
    initialsText: "text-white",
    isLightFront: false,
    isLightSurface: true,
  },
  "skyline-estate": {
    frontSurface: "bg-zinc-800",
    frontText: "text-stone-100",
    surface: "bg-stone-100",
    text: "text-zinc-900",
    subtext: "text-zinc-600",
    accent: "bg-zinc-800",
    accentBarMuted: "bg-zinc-500",
    initialsText: "text-stone-100",
    isLightFront: false,
    isLightSurface: true,
  },
  "morton-olive": {
    frontSurface: "bg-lime-950",
    frontText: "text-stone-200",
    surface: "bg-white",
    text: "text-lime-950",
    subtext: "text-lime-800",
    accent: "bg-lime-900",
    accentBarMuted: "bg-lime-300",
    initialsText: "text-stone-200",
    isLightFront: false,
    isLightSurface: true,
  },
  "shapeiva-arc": {
    frontSurface: "bg-white",
    frontText: "text-teal-800",
    surface: "bg-teal-800",
    text: "text-white",
    subtext: "text-teal-100",
    accent: "bg-teal-600",
    accentBarMuted: "bg-teal-500",
    initialsText: "text-white",
    isLightFront: true,
    isLightSurface: false,
  },
  "crimson-bold": {
    frontSurface: "bg-red-900",
    frontText: "text-white",
    surface: "bg-red-950",
    text: "text-white",
    subtext: "text-red-200",
    accent: "bg-red-500",
    accentBarMuted: "bg-red-700",
    initialsText: "text-white",
    isLightFront: false,
    isLightSurface: false,
  },
  "sunset-warm": {
    frontSurface: "bg-orange-500",
    frontText: "text-white",
    surface: "bg-orange-50",
    text: "text-orange-950",
    subtext: "text-orange-700",
    accent: "bg-orange-600",
    accentBarMuted: "bg-orange-300",
    initialsText: "text-white",
    isLightFront: false,
    isLightSurface: true,
  },
  "ocean-deep": {
    frontSurface: "bg-cyan-950",
    frontText: "text-cyan-50",
    surface: "bg-cyan-900",
    text: "text-white",
    subtext: "text-cyan-200",
    accent: "bg-cyan-400",
    accentBarMuted: "bg-cyan-700",
    initialsText: "text-cyan-950",
    isLightFront: false,
    isLightSurface: false,
  },
  "lavender-soft": {
    frontSurface: "bg-violet-100",
    frontText: "text-violet-950",
    surface: "bg-violet-50",
    text: "text-violet-950",
    subtext: "text-violet-600",
    accent: "bg-violet-600",
    accentBarMuted: "bg-violet-300",
    initialsText: "text-white",
    isLightFront: true,
    isLightSurface: true,
  },
  "copper-luxe": {
    frontSurface: "bg-amber-950",
    frontText: "text-amber-100",
    surface: "bg-stone-900",
    text: "text-amber-50",
    subtext: "text-amber-200/80",
    accent: "bg-amber-600",
    accentBarMuted: "bg-amber-800",
    initialsText: "text-amber-950",
    isLightFront: false,
    isLightSurface: false,
  },
  "slate-corporate": {
    frontSurface: "bg-slate-700",
    frontText: "text-white",
    surface: "bg-slate-100",
    text: "text-slate-900",
    subtext: "text-slate-600",
    accent: "bg-slate-800",
    accentBarMuted: "bg-slate-400",
    initialsText: "text-white",
    isLightFront: false,
    isLightSurface: true,
  },
  "berry-creative": {
    frontSurface: "bg-fuchsia-700",
    frontText: "text-white",
    surface: "bg-fuchsia-950",
    text: "text-fuchsia-50",
    subtext: "text-fuchsia-200",
    accent: "bg-fuchsia-400",
    accentBarMuted: "bg-fuchsia-600",
    initialsText: "text-fuchsia-950",
    isLightFront: false,
    isLightSurface: false,
  },
  "pine-nordic": {
    frontSurface: "bg-green-950",
    frontText: "text-green-100",
    surface: "bg-green-900",
    text: "text-white",
    subtext: "text-green-200/70",
    accent: "bg-green-400",
    accentBarMuted: "bg-green-700",
    initialsText: "text-green-950",
    isLightFront: false,
    isLightSurface: false,
  },
  "ivory-gold": {
    frontSurface: "bg-amber-50",
    frontText: "text-amber-950",
    surface: "bg-amber-50",
    text: "text-amber-950",
    subtext: "text-amber-800",
    accent: "bg-yellow-600",
    accentBarMuted: "bg-yellow-400",
    initialsText: "text-amber-950",
    isLightFront: true,
    isLightSurface: true,
  },
  "navy-gold": {
    frontSurface: "bg-blue-950",
    frontText: "text-amber-100",
    surface: "bg-blue-950",
    text: "text-white",
    subtext: "text-blue-200",
    accent: "bg-yellow-500",
    accentBarMuted: "bg-blue-800",
    initialsText: "text-blue-950",
    isLightFront: false,
    isLightSurface: false,
  },
  "rose-modern": {
    frontSurface: "bg-rose-500",
    frontText: "text-white",
    surface: "bg-rose-50",
    text: "text-rose-950",
    subtext: "text-rose-700",
    accent: "bg-rose-600",
    accentBarMuted: "bg-rose-300",
    initialsText: "text-white",
    isLightFront: false,
    isLightSurface: true,
  },
  "charcoal-minimal": {
    frontSurface: "bg-neutral-800",
    frontText: "text-neutral-100",
    surface: "bg-neutral-100",
    text: "text-neutral-900",
    subtext: "text-neutral-500",
    accent: "bg-neutral-900",
    accentBarMuted: "bg-neutral-400",
    initialsText: "text-neutral-100",
    isLightFront: false,
    isLightSurface: true,
  },
  "emerald-luxe": {
    frontSurface: "bg-emerald-950",
    frontText: "text-emerald-50",
    surface: "bg-emerald-900",
    text: "text-white",
    subtext: "text-emerald-200/80",
    accent: "bg-emerald-300",
    accentBarMuted: "bg-emerald-700",
    initialsText: "text-emerald-950",
    isLightFront: false,
    isLightSurface: false,
  },
};
