import type { ThemeStyleClasses } from "@/lib/card-theme-utils";
import type { CardTheme } from "@/lib/card-themes";
import type { ThemeCategory } from "@/lib/theme-categories";

type StudioThemeSeed = {
  id: string;
  name: string;
  description: string;
  category: ThemeCategory;
  layout: CardTheme["layout"];
  orientation: CardTheme["orientation"];
  styles: ThemeStyleClasses;
};

const studioSeeds: StudioThemeSeed[] = [
  {
    id: "studio-cohub",
    name: "Cohub Green",
    description: "Serif monogram front with green-accent partner back.",
    category: "luxury",
    layout: "studio-cohub",
    orientation: "landscape",
    styles: {
      frontSurface: "bg-[#F2F2F2]",
      frontText: "text-black",
      surface: "bg-[#F2F2F2]",
      text: "text-black",
      subtext: "text-neutral-600",
      accent: "bg-[#66BB6A]",
      accentBarMuted: "bg-neutral-300",
      initialsText: "text-black",
      isLightFront: true,
      isLightSurface: true,
    },
  },
  {
    id: "studio-austerlitz",
    name: "Austerlitz Blue",
    description: "Corporate blue front with geometric pattern back.",
    category: "professional",
    layout: "studio-austerlitz",
    orientation: "landscape",
    styles: {
      frontSurface: "bg-white",
      frontText: "text-[#1E6FD9]",
      surface: "bg-[#1E6FD9]",
      text: "text-white",
      subtext: "text-[#1E6FD9]/70",
      accent: "bg-[#1E6FD9]",
      accentBarMuted: "bg-[#1E6FD9]/20",
      initialsText: "text-[#1E6FD9]",
      isLightFront: true,
      isLightSurface: false,
    },
  },
  {
    id: "studio-rocket",
    name: "Rocket Square",
    description: "Overlapping squares with navy editorial hierarchy.",
    category: "geometric",
    layout: "studio-rocket",
    orientation: "landscape",
    styles: {
      frontSurface: "bg-white",
      frontText: "text-[#2C3E50]",
      surface: "bg-white",
      text: "text-[#2C3E50]",
      subtext: "text-[#D5D8DC]",
      accent: "bg-[#2C3E50]",
      accentBarMuted: "bg-[#D5D8DC]",
      initialsText: "text-[#2C3E50]",
      isLightFront: true,
      isLightSurface: true,
    },
  },
  {
    id: "studio-bauhaus",
    name: "Bauhaus Lines",
    description: "Monochrome geometric line grid with bold identity.",
    category: "monochrome",
    layout: "studio-bauhaus",
    orientation: "landscape",
    styles: {
      frontSurface: "bg-black",
      frontText: "text-white",
      surface: "bg-white",
      text: "text-black",
      subtext: "text-neutral-600",
      accent: "bg-black",
      accentBarMuted: "bg-neutral-300",
      initialsText: "text-white",
      isLightFront: false,
      isLightSurface: true,
    },
  },
  {
    id: "studio-golden-wave",
    name: "Golden Wave",
    description: "Organic yellow wave with landscape studio energy.",
    category: "creative",
    layout: "studio-golden-wave",
    orientation: "landscape",
    styles: {
      frontSurface: "bg-white",
      frontText: "text-neutral-900",
      surface: "bg-white",
      text: "text-neutral-900",
      subtext: "text-neutral-500",
      accent: "bg-[#F5B800]",
      accentBarMuted: "bg-[#F5B800]/30",
      initialsText: "text-[#F5B800]",
      isLightFront: true,
      isLightSurface: true,
    },
  },
  {
    id: "studio-sarah",
    name: "Sarah Blue",
    description: "Sky-blue blob with vertical designer title.",
    category: "creative",
    layout: "studio-sarah",
    orientation: "landscape",
    styles: {
      frontSurface: "bg-[#F8FAFC]",
      frontText: "text-black",
      surface: "bg-[#8EBAFF]",
      text: "text-black",
      subtext: "text-black/70",
      accent: "bg-[#8EBAFF]",
      accentBarMuted: "bg-black/10",
      initialsText: "text-black",
      isLightFront: true,
      isLightSurface: true,
    },
  },
  {
    id: "studio-florence",
    name: "Florence Arch",
    description: "Bold architectural typography on textured gray.",
    category: "typography-focused",
    layout: "studio-florence",
    orientation: "landscape",
    styles: {
      frontSurface: "bg-[#E5E5E5]",
      frontText: "text-black",
      surface: "bg-[#E5E5E5]",
      text: "text-black",
      subtext: "text-neutral-600",
      accent: "bg-black",
      accentBarMuted: "bg-neutral-400",
      initialsText: "text-black",
      isLightFront: true,
      isLightSurface: true,
    },
  },
  {
    id: "studio-adventure",
    name: "Adventure Red",
    description: "Cream and crimson split with geometric accents.",
    category: "bold",
    layout: "studio-adventure",
    orientation: "landscape",
    styles: {
      frontSurface: "bg-[#F5F5F0]",
      frontText: "text-[#D32F2F]",
      surface: "bg-[#F5F5F0]",
      text: "text-[#D32F2F]",
      subtext: "text-[#D32F2F]/70",
      accent: "bg-[#D32F2F]",
      accentBarMuted: "bg-[#D32F2F]/20",
      initialsText: "text-[#D32F2F]",
      isLightFront: true,
      isLightSurface: true,
    },
  },
  {
    id: "studio-ponto",
    name: "Ponto Blob",
    description: "Warm cream canvas with cobalt organic mark.",
    category: "minimalist",
    layout: "studio-ponto",
    orientation: "landscape",
    styles: {
      frontSurface: "bg-[#E5E0D8]",
      frontText: "text-black",
      surface: "bg-[#E5E0D8]",
      text: "text-black",
      subtext: "text-neutral-600",
      accent: "bg-[#2E5BFF]",
      accentBarMuted: "bg-neutral-300",
      initialsText: "text-black",
      isLightFront: true,
      isLightSurface: true,
    },
  },
  {
    id: "studio-business",
    name: "Business Center",
    description: "Dark geometric logo front with crisp contact back.",
    category: "geometric",
    layout: "studio-business",
    orientation: "landscape",
    styles: {
      frontSurface: "bg-white",
      frontText: "text-black",
      surface: "bg-black",
      text: "text-white",
      subtext: "text-neutral-400",
      accent: "bg-white",
      accentBarMuted: "bg-neutral-600",
      initialsText: "text-white",
      isLightFront: true,
      isLightSurface: false,
    },
  },
  {
    id: "studio-bill",
    name: "Bill Heavy",
    description: "Industrial yellow with oversized wordmark.",
    category: "bold",
    layout: "studio-bill",
    orientation: "landscape",
    styles: {
      frontSurface: "bg-[#FFEF00]",
      frontText: "text-black",
      surface: "bg-[#FFEF00]",
      text: "text-black",
      subtext: "text-black/70",
      accent: "bg-black",
      accentBarMuted: "bg-black/20",
      initialsText: "text-black",
      isLightFront: true,
      isLightSurface: true,
    },
  },
  {
    id: "studio-refresh",
    name: "Refresh Electric",
    description: "Electric blue brand front with structured contact back.",
    category: "modern",
    layout: "studio-refresh",
    orientation: "landscape",
    styles: {
      frontSurface: "bg-[#0040FF]",
      frontText: "text-white",
      surface: "bg-white",
      text: "text-[#0040FF]",
      subtext: "text-[#0040FF]/70",
      accent: "bg-[#0040FF]",
      accentBarMuted: "bg-[#0040FF]/15",
      initialsText: "text-white",
      isLightFront: false,
      isLightSurface: true,
    },
  },
  {
    id: "studio-flox",
    name: "Flox Power",
    description: "Holographic tech front with monospace contact back.",
    category: "tech-futuristic",
    layout: "studio-flox",
    orientation: "landscape",
    styles: {
      frontSurface: "bg-[#1E40FF]",
      frontText: "text-white",
      surface: "bg-[#F4F4F4]",
      text: "text-[#111827]",
      subtext: "text-[#111827]/70",
      accent: "bg-[#39FF14]",
      accentBarMuted: "bg-[#39FF14]/25",
      initialsText: "text-white",
      isLightFront: false,
      isLightSurface: true,
    },
  },
  {
    id: "studio-hello",
    name: "Hello Red",
    description: "High-impact red greeting with vertical company rail.",
    category: "bold",
    layout: "studio-hello",
    orientation: "landscape",
    styles: {
      frontSurface: "bg-[#E31B23]",
      frontText: "text-white",
      surface: "bg-white",
      text: "text-[#E31B23]",
      subtext: "text-[#E31B23]/75",
      accent: "bg-[#E31B23]",
      accentBarMuted: "bg-[#E31B23]/15",
      initialsText: "text-white",
      isLightFront: false,
      isLightSurface: true,
    },
  },
  {
    id: "studio-revive",
    name: "Revive Terra",
    description: "Terracotta restoration mark with structured back.",
    category: "professional",
    layout: "studio-revive",
    orientation: "landscape",
    styles: {
      frontSurface: "bg-[#6B341F]",
      frontText: "text-white",
      surface: "bg-white",
      text: "text-[#6B341F]",
      subtext: "text-[#6B341F]/70",
      accent: "bg-[#6B341F]",
      accentBarMuted: "bg-[#6B341F]/15",
      initialsText: "text-white",
      isLightFront: false,
      isLightSurface: true,
    },
  },
  {
    id: "studio-southern-craft",
    name: "Southern Craft",
    description: "Artisan olive and burgundy with line-grid accents.",
    category: "vintage",
    layout: "studio-southern-craft",
    orientation: "landscape",
    styles: {
      frontSurface: "bg-[#6B7B5C]",
      frontText: "text-[#F5F0E6]",
      surface: "bg-[#7A3B44]",
      text: "text-[#F5F0E6]",
      subtext: "text-[#F5F0E6]/75",
      accent: "bg-[#5E2E35]",
      accentBarMuted: "bg-[#F5F0E6]/20",
      initialsText: "text-[#F5F0E6]",
      isLightFront: false,
      isLightSurface: false,
    },
  },
  {
    id: "studio-skild",
    name: "Skild Agency",
    description: "Dark agency wordmark with clean contact back.",
    category: "creative",
    layout: "studio-skild",
    orientation: "landscape",
    styles: {
      frontSurface: "bg-[#111111]",
      frontText: "text-white",
      surface: "bg-[#F4F4F4]",
      text: "text-black",
      subtext: "text-neutral-600",
      accent: "bg-[#111111]",
      accentBarMuted: "bg-neutral-300",
      initialsText: "text-white",
      isLightFront: false,
      isLightSurface: true,
    },
  },
  {
    id: "studio-farmhouse",
    name: "Modern Farmhouse",
    description: "Serif farmhouse header with warm editorial back.",
    category: "scandinavian",
    layout: "studio-farmhouse",
    orientation: "landscape",
    styles: {
      frontSurface: "bg-[#F5F1EA]",
      frontText: "text-[#2F3E46]",
      surface: "bg-[#F5F1EA]",
      text: "text-[#2F3E46]",
      subtext: "text-[#2F3E46]/70",
      accent: "bg-[#2F3E46]",
      accentBarMuted: "bg-[#2F3E46]/15",
      initialsText: "text-[#2F3E46]",
      isLightFront: true,
      isLightSurface: true,
    },
  },
];

export const studioThemeStyles: Record<string, ThemeStyleClasses> =
  Object.fromEntries(studioSeeds.map((seed) => [seed.id, seed.styles]));

export function buildStudioCardThemes(
  base: (
    theme: Omit<
      CardTheme,
      "surface" | "text" | "subtext" | "accent" | "accentText"
    > &
      Partial<
        Pick<CardTheme, "surface" | "text" | "subtext" | "accent" | "accentText">
      >,
  ) => CardTheme,
): CardTheme[] {
  return studioSeeds.map((seed) =>
    base({
      id: seed.id,
      name: seed.name,
      description: seed.description,
      category: seed.category,
      layout: seed.layout,
      orientation: seed.orientation,
      size: "md",
      surface: seed.styles.surface,
      text: seed.styles.text,
      subtext: seed.styles.subtext,
      accent: seed.styles.accent,
      accentText: seed.styles.text,
      pro: true,
    }),
  );
}

export const STUDIO_LAYOUT_IDS = studioSeeds.map((seed) => seed.layout);
