import { BusinessCardData } from "./types";

export const cards: BusinessCardData[] = [
  {
    id: "card-1",
    side: "front",
    name: "Sagar M R",
    title: "Graphic designer",
    company: "Shapeiva",
    tagline: "Designs that define you",
    phone: "0480 272 345",
    phone2: "+91 9567 891 001",
    email: "info@shapeiva.com",
    website: "www.shapeiva.com",
    address: "14 Linden Court, Unit 4",
    initials: "SM",
    colors: {
      front: "#FFFFFF",
      back: "#0E5C56",
      accent: "#0E5C56",
      accentText: "#FFFFFF",
      onFront: "#0E5C56",
      onBack: "#FFFFFF",
      onBackMuted: "#9FCFC8",
    },
  },
  {
    id: "card-2",
    side: "back",
    name: "Eleanor Voss",
    title: "Principal architect",
    company: "Voss & Kade",
    tagline: "Structures with intent",
    phone: "647 318 5520",
    phone2: "+1 416 902 7741",
    email: "eleanor@vossandkade.com",
    website: "www.vossandkade.com",
    address: "220 Front St W, Suite 6",
    initials: "EV",
    colors: {
      front: "#FFFFFF",
      back: "#1C1A17",
      accent: "#C97B3D",
      accentText: "#1C1A17",
      onFront: "#C97B3D",
      onBack: "#F3EDE4",
      onBackMuted: "#B8AC9B",
    },
  },
];
