import { BusinessCardData } from "./types";

export const cards: BusinessCardData[] = [
  {
    id: "card-1",
    side: "front",
    name: "Neeraj Neeraj",
    title: "Full Stack Developer",
    company: "Cardify",
    tagline: "Designs that define you",
    phone: "123 456 7890",
    email: "support@cardify.com",
    website: "www.cardify.to",
    address: "X abc Court, Unit X",
    initials: "C",
    colors: {
      front: "#FFFFFF",
      back: "#0E5C56",
      accent: "#0E5C56",
      accentText: "#FFFFFF",
      onFront: "#0E5C56",
      onBack: "#FFFFFF",
      onBackMuted: "#9FCFC8",
    },
  },
  {
    id: "card-2",
    side: "back",
    name: "Neeraj Neeraj",
    title: "Full Stack Developer",
    company: "Cardify",
    tagline: "Business cards under 60 seconds",
    phone: "123 456 7890",
    email: "support@cardify.to",
    website: "www.cardify.to",
    address: "X abc court, Unit X",
    initials: "NN",
    colors: {
      front: "#FFFFFF",
      back: "#1C1A17",
      accent: "#C97B3D",
      accentText: "#1C1A17",
      onFront: "#C97B3D",
      onBack: "#F3EDE4",
      onBackMuted: "#B8AC9B",
    },
  },
];
